# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

# SOPS configuration for work secrets
keys:
  # Work-specific age key (generate with: age-keygen -o ~/.config/sops/work/keys.txt)
  - &work_age age1placeholder_work_age_key_here
  
  # Work GPG key (optional - use corporate GPG key if available)  
  - &work_gpg PLACEHOLDER_WORK_GPG_KEY_FINGERPRINT
  
  # Work laptop host key (generate during installation)
  - &work_host_ct_lt_2671 age1placeholder_ct_lt_2671_host_key

creation_rules:
  # ct-lt-2671 work laptop secrets
  - path_regex: secrets/work/hosts/ct-lt-2671/.*\.yaml$
    key_groups:
      - age:
          - *work_age
          - *work_host_ct_lt_2671
        pgp:
          - *work_gpg

  # Shared work secrets
  - path_regex: secrets/work/shared/.*\.yaml$
    key_groups:
      - age:
          - *work_age
        pgp:
          - *work_gpp