# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only
# Hardware configuration for ct-lt-2671 work laptop
# This file is usually generated by nixos-generate-config
# Replace with actual hardware configuration when installing
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # CPU configuration (placeholder - adjust based on actual hardware)
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"]; # Change to "kvm-amd" for AMD systems
  boot.extraModulePackages = [];

  # Hardware acceleration (adjust based on GPU)
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  # Audio
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Power management for laptop
  powerManagement.enable = true;
  services.thermald.enable = true; # Intel thermal management
  services.auto-cpufreq.enable = true; # CPU frequency scaling

  # Laptop-specific hardware
  services.fwupd.enable = true; # Firmware updates
  hardware.bluetooth.enable = true;

  # Graphics (placeholder - adjust based on actual GPU)
  services.xserver.videoDrivers = ["intel"]; # or "nvidia", "amdgpu"

  # Touchpad support
  services.xserver.libinput.enable = true;

  # Network hardware
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
