# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/716a5826-42b2-4896-a650-454b84e9a1f8";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FA29-91FA";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a4cb89ef-7177-4c82-9f7f-76a13045b6e1";
    fsType = "xfs";
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/20ABF45446F99E79";
    fsType = "ntfs3";
    options = [ "defaults" "rw" "uid=1000" "nofail" ];
  };

  fileSystems."/var/lib/libvirt/images" = {
    device = "/data/Linux/var/lib/libvirt/images";
    options = [ "bind" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/5af170c5-02a2-4785-bc33-c4df8307ed95"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
