# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

# SOPS configuration for personal secrets
keys:
  # Personal age key (generate with: age-keygen -o ~/.config/sops/personal/keys.txt)
  - &personal_age age1placeholder_personal_age_key_here
  
  # Personal GPG key
  - &personal_gpg PLACEHOLDER_PERSONAL_GPG_KEY_FINGERPRINT
  
  # Personal laptop host keys
  - &personal_host_DEUSEX_LINUX age1placeholder_deusex_host_key
  - &personal_host_NEO_LINUX age1placeholder_neo_host_key

creation_rules:
  # DEUSEX-LINUX personal secrets
  - path_regex: secrets/personal/hosts/DEUSEX-LINUX/.*\.yaml$
    key_groups:
      - age:
          - *personal_age
          - *personal_host_DEUSEX_LINUX
        pgp:
          - *personal_gpg

  # NEO-LINUX personal secrets  
  - path_regex: secrets/personal/hosts/NEO-LINUX/.*\.yaml$
    key_groups:
      - age:
          - *personal_age
          - *personal_host_NEO_LINUX
        pgp:
          - *personal_gpg

  # Shared personal secrets
  - path_regex: secrets/personal/shared/.*\.yaml$
    key_groups:
      - age:
          - *personal_age
        pgp:
          - *personal_gpg