# SPDX-FileCopyrightText: 2023-2026 Dom 'shymega' Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: Apache-2.0
# This file contains installer configuration secrets
# To encrypt this file, run: sops -e -i config.yaml
zerotier-network-id: "REPLACE_WITH_YOUR_ZEROTIER_NETWORK_ID"
installer-ssh-keys:
  - "REPLACE_WITH_YOUR_SSH_PUBLIC_KEY_1"
  - "REPLACE_WITH_YOUR_SSH_PUBLIC_KEY_2"
