# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only
name: Schedule CI Workflow
on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:
concurrency:
  group: gh-ref-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-inputs-update:
    uses: ./.github/workflows/flake-inputs-update.yml
    secrets: inherit
