# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

name: "Build and push to private Nix cache"
on:
  workflow_call:
jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
  build-and-push-attic:
    name: "Build and push to cache for system: ${{ matrix.hostName }}@(${{ matrix.platform }})"
    needs: nix-matrix
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - run: |
          sudo mkdir -p /etc/nix
          echo \"machine shynet-nix-attic.shymega.org.uk password ${{ secrets.GH_ATTIC_TOKEN }}\" | sudo tee /etc/nix/netrc > /dev/null
          git config --global url.\"https://${{ secrets.NIX_GH_ACTIONS_TOKEN }}@github.com\".insteadOf https://github.com
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            extra-platforms = aarch64-linux armv7l-linux armv6l-linux
            substituters = https://nix-private.attic.shymega.org.uk/shynet-nix-private-attic?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: ryanccn/attic-action@v0
        continue-on-error: true
        with:
          endpoint: "https://nix-private.attic.shymega.org.uk/shynet-nix-private-attic"
          cache: "shynet-nix-private-attic"
          token: '${{ secrets.GH_ACTIONS_ATTIC_TOKEN }}'
      - run: nix run nixpkgs#nixos-rebuild -- build --accept-flake-config --flake ".#${{ matrix.hostName }}"
