# SPDX-FileCopyrightText: 2025 Dom Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: GPL-3.0-only

name: "Nix Formatting Job"
on:
  workflow_call:
jobs:
  format-flake:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - name: Format Nix files
        run: nix fmt .
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: Update Flake inputs"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          signoff: false
          delete-branch: true
          title: "chore(lint): Format Nix files"
          branch-suffix: "short-commit-hash"
          reviewers: "shymega"
          assignees: "shymega"
          body: |
            Update Flake inputs
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
