# SPDX-FileCopyrightText: 2023-2026 Dom 'shymega' Rodriguez <shymega@shymega.org.uk>
#
# SPDX-License-Identifier: Apache-2.0
name: "Basic Flake Test"
on:
  workflow_call:
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.NIX_GH_ACTIONS_TOKEN }}
      - name: Check Flake with Nix
        run: nix flake check --accept-flake-config
